### ISSUE TITLE
Great write up and program!

### ISSUE THREAD

**Issue by rlust** [nicjansma/dht-logger#1]
I have made it all of the way on the Amazon set till Amazon API Gateway.
Looks like the menus and screens have changed.
Stuck at this point.
If you could provide any pointer to make it through the new process that would to be wonderful!

**Comment by nicjansma** [comment]
@rlust Can you share a screenshot of the point you're stuck at?

I haven't run through through the setup in a while.

**Comment by nicjansma** [comment]
Please let me know if you have details!
