### ISSUE TITLE
ThingSpeak.h

### ISSUE THREAD

**Issue by chixxi** [nicjansma/dht-logger#2]
Hi fellow home brewer

I am using your code on a photon to monitor the brewing room with my conicals. The code itself works just fine, thank you so much for publishing this!

I am trying to get ThingSpeak to log the data. Is this the ThingSpeak.h which I would have to add to the project? https://github.com/mathworks/thingspeak-arduino/blob/master/src/ThingSpeak.h

**Comment by chixxi** [comment]
Oh, wrong link, guess this one is the right one?
https://github.com/mathworks/thingspeak-particle/tree/master/firmware

Already looks much better, but I am still getting this error from the main *.ino file:
dht22.ino:232:70: invalid conversion from 'const char*' to 'long unsigned int' [-fpermissive]

**Comment by chixxi** [comment]
Oh, that was my error, entered the channel name instead of the number from the ID. All running now.

Thanks again!

**Comment by nicjansma** [comment]
Glad you got it working!  And that it's being used by a fellow homebrewer :)
